compte/urls.py
from django.urls import path
from . import views


urlpatterns = [

]

posts/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.blog_view, name='blog'),
    path('create_post/', views.create_post_view, name='create_post'),
    path('post_delete/<str:id>', views.delete_post, name='post_delete'),
    path('post_update/<str:id>', views.update_post, name='post_update'),
    path('<str:id>', views.detail_view, name='detail_view'),
]

projectimmo/urls.py
from django.contrib import admin
from django.urls import path,include

from django.contrib.auth import views as auth_views

from django.conf import settings
from django.conf.urls.static import static

# from django.conf.urls import url
from django.urls import include, re_path

from compte import views
from annonceMain.views import (
    CreateCheckoutSessionView,
    SuccessView,
    CancelView,
    stripe_webhook
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('compte/inscription/', views.inscriptionPage, name='inscription'),
    path('compte/acces/', views.accesPage, name='acces'),
    path('compte/quitter/', views.logoutUser, name='quitter'),
    path('', include('annonceMain.urls')),
   # path('', include('streaming_app.urls')),
    path('user/', views.userPage, name='user-page'),
    path('account/', views.accountSettings, name='account_settings'),
    path('', include('produit.urls')),
    path('', include('conciergerie.urls')),
    path('', include('annonce.urls')),
    path('client', include('client.urls')),
    path('commande', include('commande.urls')),
   # path('compte/', include('compte.urls')),
    path('posts/', include('posts.urls')),
    path('verification/', include('verify_email.urls')),
    path('', include('workflow.urls')),
  # path('create-post/', views.create_post_view, name='create-post'),
   # path('<int:id>/', views.detail_view, name='detail'),
    re_path('^soumission/', include('soumission.urls')),
    re_path('^soumission/validation/', include('soumission.urls')),
    # url('^soumission/request-meeting/<int:id>/', include('soumission.urls')),
    re_path('^soumission/client/', include('soumission.urls')),
    re_path(r'fp/', include('django_drf_filepond.urls')),
    re_path('create-checkout-session/<str:pk>/<int:price>', CreateCheckoutSessionView.as_view(), name='create-checkout-session'),
    path('cancel/', CancelView.as_view(), name='cancel'),
    path('success/', SuccessView.as_view(), name='success'),
    path('webhooks/stripe/', stripe_webhook, name='stripe-webhook'),
 #   path('reset_password/', auth_views.PasswordResetView.as_view(),name="reset_password"),
  #  path('reset_password_sent/', auth_views.PasswordResetDone.as_view(),name="password_reset_done"),
  #  path('reset/<uidb64>/<token>/', auth_views.PasswordConfirmView.as_view(),name="password_reset_confirm"),
  #  path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(),name="password_reset_complete"),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from django.utils.translation import gettext_lazy as _
# Create your models here.

class MyAccountManager(BaseUserManager):
    def create_user(self, email, telephone, first_name, last_name, typelocataire, password=None):
        if not email:
            raise ValueError("Entrez une adresse mail")
        if not telephone:
            raise ValueError("Entrez un nom de téléphone")
        if not last_name:
            raise ValueError("Entrez un nom de famille")
        if not first_name:
            raise ValueError("Entrez un prénom")
        if not typelocataire:
            raise ValueError("Entrez un type de locataire")

        user = self.model(
            email = self.normalize_email(email),
            telephone = telephone,
            first_name = first_name,
            last_name = last_name,
            typelocataire = typelocataire,
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, first_name, last_name, telephone, typelocataire, password):
        user = self.create_user(
            email = self.normalize_email(email),
            password = password,
            first_name = first_name,
            last_name = last_name,
            telephone = telephone,
            typelocataire = typelocataire,
        )
        user.is_admin = True
        user.is_staff = True
        user.is_superuser = True
        user.save(using = self._db)
        return user

class Account(AbstractBaseUser):
    email = models.EmailField(verbose_name="email", max_length=60, unique=True)
    date_joined = models.DateTimeField(verbose_name='date joined', auto_now_add=True)
    last_login = models.DateTimeField(verbose_name='last login', auto_now=True)
    is_admin = models.BooleanField(default=False)
    is_active = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    telephone = models.CharField(max_length=10)
    photo_profil = models.ImageField(blank=True)
    photo_identite = models.ImageField(blank=True)
    photo_stream = models.ImageField(blank=True)

    class TypePackages(models.TextChoices):
        bronze = 'BRON', _('Bronze')
        silver = 'SILV', _('Silver')
        gold = 'GOLD', _('Gold')

    packages_type = models.CharField(
        max_length=4,
        choices=TypePackages.choices,
        default=TypePackages.bronze,
        verbose_name="Package"
    )
    class TypeLocataire(models.TextChoices):
        particulier = 'PART', _('Particulier')
        profesionnel = 'PROF', _('Profesionnel')

    typelocataire = models.CharField(
        max_length=4,
        choices=TypeLocataire.choices,
        default=TypeLocataire.particulier,
        verbose_name="Type de loueur"
    )

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['first_name','last_name','telephone','typelocataire']

    objects = MyAccountManager()

    def __str__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        return self.is_admin

    def has_module_perms(self, app_label):
        return True

class Address(models.Model):
    account = models.OneToOneField(
        Account,
        on_delete=models.CASCADE,
        primary_key=True,
        default='',
    )
    rue = models.CharField(blank=True, max_length=20)
    voie = models.CharField(blank=True, max_length=35)
    ville = models.CharField(blank=True, max_length=20)
    region = models.CharField(blank=True, max_length=20)
    zipCode = models.CharField(blank=True, max_length=5)
    pays = models.CharField(blank=True, max_length=20)

annonce/models.py
from django.utils.translation import gettext_lazy as _

from django.db import models
from django.conf import settings
from django.forms.models import ModelForm
from django.forms.widgets import CheckboxSelectMultiple
from django.db.models import IntegerField, Model
from django.core.validators import MaxValueValidator, MinValueValidator
from django.forms import CheckboxSelectMultiple
# Create your models here.


class AdressAnnonce(models.Model):

    rue = models.CharField(blank=True, max_length=20)
    voie = models.CharField(blank=True, max_length=35)
    ville = models.CharField(blank=True, max_length=20)
    region = models.CharField(blank=True, max_length=20)
    zipCode = models.CharField(blank=True, max_length=5)
    pays = models.CharField(blank=True, max_length=20)

class Equipements(models.Model):
    nom = models.CharField(max_length=200, null=True)

    def __str__(self):
        return self.nom

class CategorieService(models.Model):
    nom = models.CharField(max_length=200, null=True)

class Services(models.Model):
    nom = models.CharField(max_length=200, null=True)
    price = models.FloatField(max_length=50, blank=True, null=True)

    class Categorie(models.TextChoices):
        Lifestyle = 'life', _('Lifestyle')
        Bien_etre = 'bien', _('Bien être')
        Services_quotidien = 'quot', _('Services quotidiens')
        Loisirs = 'lois', _('Loisirs')
        Transport = 'trsp', _('Transports')
        Installation = 'inst', _('Installation')

    categorie = models.CharField(
        max_length=4,
        choices=Categorie.choices,
        default=Categorie.Lifestyle,
        verbose_name="Categorie Service"
    )
    def __str__(self):
        return self.nom


class Charges(models.Model):
    nom = models.CharField(max_length=200, null=True, unique=True)

    def __str__(self):
        return self.nom

class Annonce(models.Model):

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        null=True,
        on_delete=models.CASCADE,
        unique=False
    )
    class TypeHebergement(models.TextChoices):
        Appartemment = 'APPT', _('Appartemment')
        Maison = 'MAIS', _('Maison')
        Studio = 'STUD', _('Studio')
        Autre = 'OTHR', _('Autre')

    hebergement_choice = models.CharField(
        max_length=4,
        choices=TypeHebergement.choices,
        default=TypeHebergement.Appartemment,
        verbose_name="Type d'hébergement"
    )

    class TypeLocation(models.TextChoices):
        logement_entier = 'ENTR', _('Logement entier')
        chambre_privee = 'PRIV', _('Chambre privée')
        chambre_partagee = 'PART', _('Chambre partagée')

    type_location_choices = models.CharField(
        max_length=4,
        choices=TypeLocation.choices,
        default=TypeLocation.logement_entier,
        verbose_name="Location partielle ou totale"
    )

    categorie_logement = models.CharField(max_length=50, blank=True)
    titre_logement = models.CharField(max_length=50, blank=True)
    description = models.TextField(blank=True)
    nombre_personne = IntegerField(
        default=1,
        validators=[
            MaxValueValidator(20),
            MinValueValidator(1)
        ],
        blank=True
    )
    pieces_couchage = IntegerField(
        default=1,
        validators=[
            MaxValueValidator(10),
            MinValueValidator(1)
        ],
        blank=True
    )
    equipements = models.ManyToManyField(Equipements, blank=True)
    services = models.ManyToManyField(Services, blank=True)
    categorie_service = models.ManyToManyField(CategorieService, blank=True)
    charges = models.ManyToManyField(Charges, blank=True)
    dureeLocationMini = models.CharField(blank=True,null=True, max_length=50)
    dureeLocationMaxi = models.CharField(blank=True,null=True, max_length=50)
    loyer_tc = models.FloatField(max_length=50, blank=True, null=True)
    charges_loyer = models.FloatField(max_length=50, blank=True, null=True)
    reservation = models.OneToOneField(
        settings.AUTH_USER_MODEL,
        null=True,
        on_delete=models.CASCADE,
        unique=False,
        related_name = 'user_reserved'
    )
    reserved = models.BooleanField(default=False)
    address = models.OneToOneField(
        AdressAnnonce,
        on_delete=models.CASCADE,
        null=True,
    )

class ImageLogement(models.Model):
    annonce = models.ForeignKey(Annonce, on_delete=models.CASCADE)
    images = models.FileField(upload_to='images/')

class Calendrier(models.Model):
    annonce = models.ForeignKey(Annonce, on_delete=models.CASCADE)
    calendrier_debut = models.DateField(blank=True, null=True)
    calendrier_fin = models.DateField(blank=True, null=True)
    class Disponibilité(models.TextChoices):
        disponible = 'disp', _('Disponible')
        indisponible = 'indp', _('Indisponible')

    disponibilite = models.CharField(
        max_length=4,
        choices=Disponibilité.choices,
        default=Disponibilité.disponible,
        verbose_name="Disponibilité"
    )

class Condition(models.Model):
    annonce = models.OneToOneField(
        Annonce,
        on_delete=models.CASCADE,
        primary_key=True,
    )
    CHOICES_APRES = (
        ('1', '12h00'),
        ('2', '12h30'),
        ('3', '13h00'),
        ('4', '13h30'),
        ('5', '14h00'),
        ('6', '14h30'),
        ('7', '15h00'),
        ('8', '15h30'),
        ('9', '16h00'),
        ('10', '16h30'),
        ('11', '17h00'),
        ('12', '17h30'),
        ('13', '18h00'),
        ('14', '18h30'),
        ('15', '19h00'),
        ('16', '19h30'),
        ('17', '20h00'),
        ('18', '20h30'),
        ('19', '21h00'),
        ('19', '21h30'),
        ('19', '22h00'),
    )

    heure_arrivee_apres = models.CharField(
        max_length=10,
        choices=CHOICES_APRES,
        default="flexible",
        verbose_name="Heure d'arrivée(après)"
    )
    CHOICES_AVANT = (
        ('1', '14h00'),
        ('2', '14h30'),
        ('3', '15h00'),
        ('4', '15h30'),
        ('5', '16h00'),
        ('6', '16h30'),
        ('7', '17h00'),
        ('8', '17h30'),
        ('9', '18h00'),
        ('10', '18h30'),
        ('11', '19h00'),
        ('12', '19h30'),
        ('13', '20h00'),
        ('14', '20h30'),
        ('15', '21h00'),
        ('16', '21h30'),
        ('17', '22h00'),
    )
    heure_arrivee_avant = models.CharField(
        max_length=10,
        choices=CHOICES_AVANT,
        default="flexible",
        verbose_name="Heure d'arrivée(avant)"
    )

    CHOICES_DEPART = (
        ('1','9h00'),
        ('2','9h30'),
        ('3','10h00'),
        ('4','10h30'),
        ('5','11h00'),
        ('6','11h30'),
        ('7','12h00'),
        ('8','12h30'),
        ('9', '13h00'),
        ('10', '13h30'),
        ('11', '14h00'),
        ('12', '14h30'),
        ('13', '15h00'),
        ('14', '15h30'),
        ('15', '16h00'),
        ('16', '16h30'),
        ('17', '17h00'),
        ('18', '17h30'),
        ('19', '18h00'),
    )

    heure_depart = models.CharField(
        max_length=10,
        choices=CHOICES_DEPART,
        default="flexible",
        verbose_name="Heure de départ(avant)"
    )

    choice_bool = [(True, 'Oui'), (False, 'Non')]
    accessible_handicape = models.BooleanField(choices=choice_bool, default=1)
    fumeur_accepte = models.BooleanField(choices=choice_bool, default=1)
    animaux_accepte = models.BooleanField(choices=choice_bool, default=1)

class Diagnostic(models.Model):
    annonce = models.OneToOneField(
        Annonce,
        on_delete=models.CASCADE,
        primary_key=True,
        default='',
    )
    choice_bool = [(True, 'Oui'), (False, 'Non')]
    gaz = models.BooleanField(choices=choice_bool, default=1)
    fumee = models.BooleanField('Détecteur de fumée', default=False)
    carbone = models.BooleanField('Détecteur de monoxyde de carbone', default=False)
    extincteur = models.BooleanField('Extincteur', default=False)
    consommationNrj = models.IntegerField(default=1, blank=True)
    emissionGaz = models.IntegerField(default=1, blank=True)
    docPerformance = models.FileField(blank=True)
    risqueNaturel = models.FileField(blank=True)
    risquePlomb = models.FileField(blank=True)
    interieurElecGaz = models.FileField(blank=True)
    amianteDoc = models.FileField(blank=True)
    copopriete = models.FileField(blank=True)

compte/models.py
from django.db import models

# Create your models here.

compte/views.py
from django.shortcuts import render, redirect
from commande.models import Commande
from client.models import Client
from django.http import HttpResponse
from django.contrib.auth.forms import UserCreationForm
from .forms import CreerUtilisateur
from .forms import CustomerForm

from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from client.views import liste_clients
from .decorators import unauthenticated_user
from django.contrib.auth.models import Group
from django.contrib.auth.decorators import login_required
from .decorators import allowed_users, admin_only


# Create your views here.
@unauthenticated_user
def inscriptionPage(request):
    form=CreerUtilisateur()
    if request.method=='POST':
        form=CreerUtilisateur(request.POST)
        if form.is_valid():
                user=form.save()
                username = form.cleaned_data.get('username')
                group = Group.objects.get(name='customer')
                user.groups.add(group)
                Client.objects.create(
                    user=user,
                    nom=user.username,
                )
                messages.success(request,'compte cree avec succes pour '+username)
                return redirect('acces')
    context={'form':form}
    return render(request,'compte/inscription.html',context)

@unauthenticated_user
def accesPage(request):
    return render(request, 'index.html')

def logoutUser(request):
    logout(request)
    return redirect('acces')


# Create your views here.
@login_required(login_url='acces')
@allowed_users(allowed_roles=['customer'])
def userPage(request):
    commandes=request.user.client.commande_set.all()
    print(commandes)
    commande_total = commandes.count()
    commande_livre = commandes.filter(status='Livre').count()
    commande_en_cours = commandes.filter(status='En instance').count()
    context = {'commandes': commandes,
               'commande_total': commande_total,
               'commande_livre': commande_livre,
               'commande_en_cours': commande_en_cours
               }
    return render(request,'user.html',context)

@login_required(login_url='acces')
@allowed_users(allowed_roles=['customer'])
def accountSettings(request):
	client = request.user.client
	form = CustomerForm(instance=client)

	if request.method == 'POST':
		form = CustomerForm(request.POST, request.FILES,instance=client)
		if form.is_valid():
			form.save()


	context = {'form':form}
	return render(request, 'account/account_settings.html', context)

templates/compte/profile_annonce.html
{% extends 'main.html' %}
{% block content %}

<hr>
<div class="container bootstrap snippet">
    <div class="row">
  		<div class="col-sm-10"><h1>{{request.user.first_name}} {{request.user.last_name}}</h1></div>
    </div>
    <div class="row">
  		<div class="col-sm-3"><!--left col-->


      <div class="text-center">
        <img src="{{request.user.photo_profil.url}}" class="avatar img-circle img-thumbnail" alt="avatar">
      </div></hr><br>


          <div class="card mb-3">
            <div class="card-header">Coordonnées <i class="fa fa-link fa-1x"></i></div>
            <div class="card-body"><span><small id="emailHelp" class="form-text text-muted">Votre adresse actuelle : {{ address.rue }} {{address.voie}}, {{address.ville}} - {{address.zipCode}}</small></span>
            <hr>
                <small class="form-text text-muted">téléphone - {{request.user.telephone}}</small>
                <hr>
                <small class="form-text text-muted">Email - {{request.user.email}}</small>
            </div>
          </div>


          <ul class="list-group">
            <li class="list-group-item text-muted">Activité <i class="fa fa-dashboard fa-1x"></i></li>
              <li class="list-group-item "><span class=""><strong>Annonces</strong></span> <span class="pull-right">{{annonce|length}}</span></li>
            <li class="list-group-item"><span class="pull-left"><strong>Location</strong></span>
                {% if reservation.reserved %} <span class="bg-success text-white p-2">En cours</span>
                {% else %} <span class="bg-secondary text-white p-3">Aucune location</span></li> {% endif %}
          </ul>


        </div><!--/col-3-->
    	<div class="col-sm-9">
            <ul class="nav nav-tabs">
                <li class="nav-item active"><a data-toggle="tab" href="#home" class="nav-link">Informations utilisateur</a></li>
                <li class="nav-item"><a data-toggle="tab" href="#messages" class="nav-link">Locations</a></li>
                <li class="nav-item"><a data-toggle="tab" href="#settings" class="nav-link">Workflow</a></li>
                <li class="nav-item"><a data-toggle="tab" href="#diagnostic" class="nav-link">Diagnostic</a></li>
              </ul>


          <div class="tab-content">
            <div class="tab-pane active" id="home">
                <hr>
                      <div class="col-6">
                          <h2>Nom : {{request.user.last_name}}</h2>
                      </div>
              <hr>
                <div class="col-6">
                          <h2>Prenom : {{request.user.first_name}}</h2>
                      </div>
              <hr>
                <div class="col-6">
                          <h3>Type locataire :{{request.user.get_typelocataire_display}}</h3>
                      </div>

             </div><!--/tab-pane-->

             <div class="tab-pane" id="messages">

               <h2></h2>

               <hr>
                <div class="col-md-4 col-sm-6 mb-4 pb-2">
                    <div class="list-card bg-white h-100 rounded overflow-hidden position-relative shadow-sm">
                        <div class="list-card-image">
                            <div class="star position-absolute"><span class="badge badge-success"><i class="icofont-star"></i> 3.1 (300+)</span></div>
                            <div class="favourite-heart text-danger position-absolute"><a href="#"><i class="icofont-heart"></i></a></div>
                            <div class="member-plan position-absolute"><span class="badge badge-dark">{{reservation.categorie_logement}}</span></div>
                                <a href="#">
                                            <img src="img/list/5.png" class="img-fluid item-img">
                                        </a>
                                    </div>
                                    <div class="p-3 position-relative">
                                        <div class="list-card-body">
                                            <h6 class="mb-1"><a href="#" class="text-black">{{reservation.titre_logement}}</a></h6>
                                            <p class="text-gray mb-3">Services :{% for categorie in reservation.categorie_service.all %} {{categorie.nom}},  {% endfor %}</p>
                                            <p class="text-gray mb-3 time"><span class="bg-light text-dark rounded-sm pl-2 pb-1 pt-1 pr-2"><i class="icofont-wall-clock"></i> {{reservation.loyer_tc}} €</span> <span class="float-right text-black-50"> {{reservation.nombre_personne}} personne(s)</span></p>
                                        </div>
                                        <div class="list-card-badge">
                                            <span class="badge badge-success">{{reservation.get_hebergement_choice_display}}</span>                 <small id="emailHelp" class="form-text text-muted"> {{ reservation.address.rue }} {{reservation.address.voie}}, {{reservation.address.ville}} - {{reservation.address.zipCode}}</small>

                                        </div>
                                    </div>
                                </div>
                            </div>
             </div><!--/tab-pane-->
             <div class="tab-pane" id="settings">
                  <hr>
                 {% load crispy_forms_tags %}
                 {% load widget_tweaks %}

                  <form class="form" action="##" method="post" id="registrationForm">
                    {% for field in form %}
                      {% if field == form.planificateur_visite %}
                            <div class="col-12">
                                <p>Jours de visite : {{ workflow.planificateur_visite }}</p>
                            </div>
                      {% elif field == form.user %}
                            <div></div>
                      {% elif field == form.type_visite %}
                            <div class="col-12">
                                <p>Type de visite : {{ workflow.get_type_visite_display}}</p>
                            </div>
                      {% elif field == form.document_paye or field == form.document_avis or field == form.document_quittance %}
                            <div class="col-12">
                                <p class="bg-dark text-white">Fichiers</p>
                            </div>

                      {% else %}
                      {{ field|attr:"readonly"|as_crispy_field }}
                      {% endif %}
                      {% endfor %}
              	</form>
                    <hr>
                 <span>Votre adresse actuelle : {{ workflow.address.rue }} {{workflow.address.voie}}, {{workflow.address.ville}} - {{workflow.address.zipCode}}</span>
                    <hr>
                    Date de réunion sélectionnée : {{ workflow.date_reunion }}
                    <hr>
                 <h2>Commentaires : </h2>
                    {% for nek in workflow.commentaire_nek.all %}
                       <div class="col-6 mt-2">
                        <div class="list-group">
                          <a href="#" class="list-group-item list-group-item-action flex-column align-items-start">
                            <div class="d-flex w-100 justify-content-between">
                              <small class="text-danger">Nek</small>
                            </div>
                            <p class="mb-1">{{nek.commentaire}}</p>
                            <small>{{forloop.counter}}</small>
                          </a>
                        </div>
                           </div>
                    {% endfor %}
                    {% for demeya in workflow.commentaire_demaya.all %}
                       <div class="offset-6 col-6 mt-2">
                        <div class="list-group">
                          <a href="#" class="list-group-item list-group-item-action flex-column bg-success align-items-start">
                            <div class="d-flex w-100 justify-content-between">
                              <small class="text-warning">Demeya</small>
                            </div>
                            <p class="mb-1 text-white">{{demeya.commentaire}}</p>
                            <small>{{forloop.counter}}</small>
                          </a>
                        </div>
                           </div>
                    {% endfor %}

              </div>
        <div class="tab-pane" id="diagnostic">
                <hr>
            <form method="post" action="">
                {% csrf_token %}
                      <div class="col-12" id="nek_resp">
                        <label for="commentaire_nek">Bilan semaine</label>
                        <div class="row">
                            <div class="col-8">
                                <textarea class="form-control" name="commentaire_bilan" required></textarea>
                                <input type="datetime-local" id="bilan-semaine"
                                   name="bilan_semaine" value="2020-06-12T19:30"
                                   min="2020-06-07T00:00">
                            </div>
                            <div class="col-4">
                                <button type="button" class="btn btn-primary add"> + </button>
                                <button type="button" class="btn btn-danger remove"> - </button>
                            </div>
                        </div>
                        <input type="hidden" value="1" id="total_chq">
                    </div>
                <input type="submit" name="Envoyer" class="btn btn-primary mt-3 mb-5">
            </form>
            <h2>Bilan actuels : </h2>
                    {% for nek in workflow.bilan_semaine.all %}
                       <div class="col-6 mt-2">
                        <div class="list-group">
                          <a href="#" class="list-group-item list-group-item-action flex-column align-items-start">
                            <div class="d-flex w-100 justify-content-between">
                              <small class="text-danger">{{nek.date}}</small>
                            </div>
                            <p class="mb-1">{{nek.commentaire}}</p>
                            <small>{{forloop.counter}}</small>
                          </a>
                        </div>
                           </div>
                    {% endfor %}
             </div><!--/tab-pane-->

              </div><!--/tab-pane-->

          </div><!--/tab-content-->

        </div><!--/col-9-->
    </div><!--/row-->
<script>
    window.addEventListener('load', (event) => {

    $('.add').on('click', add);
    $('.remove').on('click', remove);
        function add(){
          var new_resp = parseInt($('#total_chq').val())+1;
          var new_input="<div id='new_" + new_resp +  "' class='col-8 mb-1 mt-1'> \
            <textarea class='form-control' name='commentaire_bilan' required></textarea> \
                                <input type='datetime-local' id='bilan-semaine' \
                                   name='bilan_semaine' value='2020-06-12T19:30' \
                                   min='2020-06-07T00:00'> \
          </div>"

          $('#nek_resp').append(new_input);
          $('#total_chq').val(new_resp)
        }
        function remove(){
          var resp = $('#total_chq').val();
          if(resp>1){
            $('#new_'+resp).remove();
            $('#total_chq').val(resp-1);
          }
          }
     })
    </script>
{% endblock %}