annonce/urls.py
# from django.conf.urls import url
from django.urls import re_path
from django.contrib import admin
from django.urls import path
from . import views
from .views import VerificationView
urlpatterns = [
    path('creer-annonce', views.create_annonce, name='creer-annonce'),
    path('register', views.inscriptionPage, name='register'),
    path('login-annonce', views.login_user, name='login-annonce'),
    path('logout-annonce', views.logout_annonce, name='logout-annonce'),
    path('logged-annonce', views.logged_annonce, name='logged-annonce'),
    path('annonce-profil', views.profile_annonce, name='annonce-profil'),
    path('activate/<uidb64>/<token>', VerificationView.as_view(), name='activate'),
    path('annonce/gerer-annonce', views.gerer_annonce, name='gerer-annonce'),
    path('annonce/dashboard/<str:pk>', views.dashboard_view, name='dashboard-annonce'),
    path('annonce/dashboard/description/<str:pk>/', views.description_view, name='dashboard-description'),
    path('annonce/dashboard/dureeLocation/<str:pk>/', views.dureeLocation_view, name='dashboard-dureelocation'),
    path('annonce/dashboard/equipment/<str:pk>/', views.equipment_view, name='dashboard-equipment'),
    path('annonce/dashboard/loyer/<str:pk>/', views.loyer_view, name='dashboard-loyer'),
    path('annonce/dashboard/photos/<str:pk>/', views.image_view, name='dashboard-image'),
    path('annonce/dashboard/photos/delete/<str:pk>/', views.delete_image, name='delete-image'),
    path('annonce/dashboard/calendrier/<str:pk>/', views.calendrier, name='dashboard-calendrier'),
    path('annonce/dashboard/calendrier/create/<str:pk>/', views.create_calendrier, name='create-calendrier'),
    path('annonce/dashboard/calendrier/edit/<str:pk>/', views.edit_calendrier, name='calendrier-edit'),
    path('annonce/dashboard/calendrier/delete/<str:pk>/', views.delete_calendrier, name='calendrier-delete'),
    path('annonce/dashboard/calendrier/delete_confirm/<str:pk>/', views.delete_calendrier_confirm, name='calendrier-delete-confirm'),
    path('annonce/dashboard/conditions/<str:pk>/', views.condition_view, name='dashboard-condition'),
    path('annonce/dashboard/diagnostic/<str:pk>/', views.diagnsotic_view, name='dashboard-diagnostic'),
    path('annonce/dashboard/coordonnee_user/<str:pk>/', views.user_view_dashboard, name='dashboard-usercoord'),
    path('annonce/dashboard/verif/<str:pk>/', views.verification_view, name='dashboard-verif'),
    path('annonce/dashboard/sign/get_signing_url', views.embeded_signing_ceremony, name='get_signing_url'),
    path('annonce/dashboard/sign/get_access_code', views.get_access_code, name='get_access_code'),
    path('annonce/dashboard/sign/auth_login', views.auth_login, name='auth_login'),
    #url(r'^sign_completed/$', views.sign_complete, name='sign_completed'),
]

posts/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.blog_view, name='blog'),
    path('create_post/', views.create_post_view, name='create_post'),
    path('post_delete/<str:id>', views.delete_post, name='post_delete'),
    path('post_update/<str:id>', views.update_post, name='post_update'),
    path('<str:id>', views.detail_view, name='detail_view'),
]

projectimmo/urls.py
from django.contrib import admin
from django.urls import path,include

from django.contrib.auth import views as auth_views

from django.conf import settings
from django.conf.urls.static import static

# from django.conf.urls import url
from django.urls import include, re_path

from compte import views
from annonceMain.views import (
    CreateCheckoutSessionView,
    SuccessView,
    CancelView,
    stripe_webhook
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('compte/inscription/', views.inscriptionPage, name='inscription'),
    path('compte/acces/', views.accesPage, name='acces'),
    path('compte/quitter/', views.logoutUser, name='quitter'),
    path('', include('annonceMain.urls')),
   # path('', include('streaming_app.urls')),
    path('user/', views.userPage, name='user-page'),
    path('account/', views.accountSettings, name='account_settings'),
    path('', include('produit.urls')),
    path('', include('conciergerie.urls')),
    path('', include('annonce.urls')),
    path('client', include('client.urls')),
    path('commande', include('commande.urls')),
   # path('compte/', include('compte.urls')),
    path('posts/', include('posts.urls')),
    path('verification/', include('verify_email.urls')),
    path('', include('workflow.urls')),
  # path('create-post/', views.create_post_view, name='create-post'),
   # path('<int:id>/', views.detail_view, name='detail'),
    re_path('^soumission/', include('soumission.urls')),
    re_path('^soumission/validation/', include('soumission.urls')),
    # url('^soumission/request-meeting/<int:id>/', include('soumission.urls')),
    re_path('^soumission/client/', include('soumission.urls')),
    re_path(r'fp/', include('django_drf_filepond.urls')),
    re_path('create-checkout-session/<str:pk>/<int:price>', CreateCheckoutSessionView.as_view(), name='create-checkout-session'),
    path('cancel/', CancelView.as_view(), name='cancel'),
    path('success/', SuccessView.as_view(), name='success'),
    path('webhooks/stripe/', stripe_webhook, name='stripe-webhook'),
 #   path('reset_password/', auth_views.PasswordResetView.as_view(),name="reset_password"),
  #  path('reset_password_sent/', auth_views.PasswordResetDone.as_view(),name="password_reset_done"),
  #  path('reset/<uidb64>/<token>/', auth_views.PasswordConfirmView.as_view(),name="password_reset_confirm"),
  #  path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(),name="password_reset_complete"),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

annonce/models.py
from django.utils.translation import gettext_lazy as _

from django.db import models
from django.conf import settings
from django.forms.models import ModelForm
from django.forms.widgets import CheckboxSelectMultiple
from django.db.models import IntegerField, Model
from django.core.validators import MaxValueValidator, MinValueValidator
from django.forms import CheckboxSelectMultiple
# Create your models here.


class AdressAnnonce(models.Model):

    rue = models.CharField(blank=True, max_length=20)
    voie = models.CharField(blank=True, max_length=35)
    ville = models.CharField(blank=True, max_length=20)
    region = models.CharField(blank=True, max_length=20)
    zipCode = models.CharField(blank=True, max_length=5)
    pays = models.CharField(blank=True, max_length=20)

class Equipements(models.Model):
    nom = models.CharField(max_length=200, null=True)

    def __str__(self):
        return self.nom

class CategorieService(models.Model):
    nom = models.CharField(max_length=200, null=True)

class Services(models.Model):
    nom = models.CharField(max_length=200, null=True)
    price = models.FloatField(max_length=50, blank=True, null=True)

    class Categorie(models.TextChoices):
        Lifestyle = 'life', _('Lifestyle')
        Bien_etre = 'bien', _('Bien être')
        Services_quotidien = 'quot', _('Services quotidiens')
        Loisirs = 'lois', _('Loisirs')
        Transport = 'trsp', _('Transports')
        Installation = 'inst', _('Installation')

    categorie = models.CharField(
        max_length=4,
        choices=Categorie.choices,
        default=Categorie.Lifestyle,
        verbose_name="Categorie Service"
    )
    def __str__(self):
        return self.nom


class Charges(models.Model):
    nom = models.CharField(max_length=200, null=True, unique=True)

    def __str__(self):
        return self.nom

class Annonce(models.Model):

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        null=True,
        on_delete=models.CASCADE,
        unique=False
    )
    class TypeHebergement(models.TextChoices):
        Appartemment = 'APPT', _('Appartemment')
        Maison = 'MAIS', _('Maison')
        Studio = 'STUD', _('Studio')
        Autre = 'OTHR', _('Autre')

    hebergement_choice = models.CharField(
        max_length=4,
        choices=TypeHebergement.choices,
        default=TypeHebergement.Appartemment,
        verbose_name="Type d'hébergement"
    )

    class TypeLocation(models.TextChoices):
        logement_entier = 'ENTR', _('Logement entier')
        chambre_privee = 'PRIV', _('Chambre privée')
        chambre_partagee = 'PART', _('Chambre partagée')

    type_location_choices = models.CharField(
        max_length=4,
        choices=TypeLocation.choices,
        default=TypeLocation.logement_entier,
        verbose_name="Location partielle ou totale"
    )

    categorie_logement = models.CharField(max_length=50, blank=True)
    titre_logement = models.CharField(max_length=50, blank=True)
    description = models.TextField(blank=True)
    nombre_personne = IntegerField(
        default=1,
        validators=[
            MaxValueValidator(20),
            MinValueValidator(1)
        ],
        blank=True
    )
    pieces_couchage = IntegerField(
        default=1,
        validators=[
            MaxValueValidator(10),
            MinValueValidator(1)
        ],
        blank=True
    )
    equipements = models.ManyToManyField(Equipements, blank=True)
    services = models.ManyToManyField(Services, blank=True)
    categorie_service = models.ManyToManyField(CategorieService, blank=True)
    charges = models.ManyToManyField(Charges, blank=True)
    dureeLocationMini = models.CharField(blank=True,null=True, max_length=50)
    dureeLocationMaxi = models.CharField(blank=True,null=True, max_length=50)
    loyer_tc = models.FloatField(max_length=50, blank=True, null=True)
    charges_loyer = models.FloatField(max_length=50, blank=True, null=True)
    reservation = models.OneToOneField(
        settings.AUTH_USER_MODEL,
        null=True,
        on_delete=models.CASCADE,
        unique=False,
        related_name = 'user_reserved'
    )
    reserved = models.BooleanField(default=False)
    address = models.OneToOneField(
        AdressAnnonce,
        on_delete=models.CASCADE,
        null=True,
    )

class ImageLogement(models.Model):
    annonce = models.ForeignKey(Annonce, on_delete=models.CASCADE)
    images = models.FileField(upload_to='images/')

class Calendrier(models.Model):
    annonce = models.ForeignKey(Annonce, on_delete=models.CASCADE)
    calendrier_debut = models.DateField(blank=True, null=True)
    calendrier_fin = models.DateField(blank=True, null=True)
    class Disponibilité(models.TextChoices):
        disponible = 'disp', _('Disponible')
        indisponible = 'indp', _('Indisponible')

    disponibilite = models.CharField(
        max_length=4,
        choices=Disponibilité.choices,
        default=Disponibilité.disponible,
        verbose_name="Disponibilité"
    )

class Condition(models.Model):
    annonce = models.OneToOneField(
        Annonce,
        on_delete=models.CASCADE,
        primary_key=True,
    )
    CHOICES_APRES = (
        ('1', '12h00'),
        ('2', '12h30'),
        ('3', '13h00'),
        ('4', '13h30'),
        ('5', '14h00'),
        ('6', '14h30'),
        ('7', '15h00'),
        ('8', '15h30'),
        ('9', '16h00'),
        ('10', '16h30'),
        ('11', '17h00'),
        ('12', '17h30'),
        ('13', '18h00'),
        ('14', '18h30'),
        ('15', '19h00'),
        ('16', '19h30'),
        ('17', '20h00'),
        ('18', '20h30'),
        ('19', '21h00'),
        ('19', '21h30'),
        ('19', '22h00'),
    )

    heure_arrivee_apres = models.CharField(
        max_length=10,
        choices=CHOICES_APRES,
        default="flexible",
        verbose_name="Heure d'arrivée(après)"
    )
    CHOICES_AVANT = (
        ('1', '14h00'),
        ('2', '14h30'),
        ('3', '15h00'),
        ('4', '15h30'),
        ('5', '16h00'),
        ('6', '16h30'),
        ('7', '17h00'),
        ('8', '17h30'),
        ('9', '18h00'),
        ('10', '18h30'),
        ('11', '19h00'),
        ('12', '19h30'),
        ('13', '20h00'),
        ('14', '20h30'),
        ('15', '21h00'),
        ('16', '21h30'),
        ('17', '22h00'),
    )
    heure_arrivee_avant = models.CharField(
        max_length=10,
        choices=CHOICES_AVANT,
        default="flexible",
        verbose_name="Heure d'arrivée(avant)"
    )

    CHOICES_DEPART = (
        ('1','9h00'),
        ('2','9h30'),
        ('3','10h00'),
        ('4','10h30'),
        ('5','11h00'),
        ('6','11h30'),
        ('7','12h00'),
        ('8','12h30'),
        ('9', '13h00'),
        ('10', '13h30'),
        ('11', '14h00'),
        ('12', '14h30'),
        ('13', '15h00'),
        ('14', '15h30'),
        ('15', '16h00'),
        ('16', '16h30'),
        ('17', '17h00'),
        ('18', '17h30'),
        ('19', '18h00'),
    )

    heure_depart = models.CharField(
        max_length=10,
        choices=CHOICES_DEPART,
        default="flexible",
        verbose_name="Heure de départ(avant)"
    )

    choice_bool = [(True, 'Oui'), (False, 'Non')]
    accessible_handicape = models.BooleanField(choices=choice_bool, default=1)
    fumeur_accepte = models.BooleanField(choices=choice_bool, default=1)
    animaux_accepte = models.BooleanField(choices=choice_bool, default=1)

class Diagnostic(models.Model):
    annonce = models.OneToOneField(
        Annonce,
        on_delete=models.CASCADE,
        primary_key=True,
        default='',
    )
    choice_bool = [(True, 'Oui'), (False, 'Non')]
    gaz = models.BooleanField(choices=choice_bool, default=1)
    fumee = models.BooleanField('Détecteur de fumée', default=False)
    carbone = models.BooleanField('Détecteur de monoxyde de carbone', default=False)
    extincteur = models.BooleanField('Extincteur', default=False)
    consommationNrj = models.IntegerField(default=1, blank=True)
    emissionGaz = models.IntegerField(default=1, blank=True)
    docPerformance = models.FileField(blank=True)
    risqueNaturel = models.FileField(blank=True)
    risquePlomb = models.FileField(blank=True)
    interieurElecGaz = models.FileField(blank=True)
    amianteDoc = models.FileField(blank=True)
    copopriete = models.FileField(blank=True)

templates/annonce/search/annonce_result.html
{% extends 'main.html' %}
{% block content %}
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript"></script>
<script src="https://polyfill.io/v3/polyfill.min.js?version=3.52.1&features=fetch"></script>
<script src="https://js.stripe.com/v3/"></script>
<div class="container">
    <div class="row">
        <div class="col-12">
            <h1>{{annonce.titre_logement}}</h1>
            <p>{{annonce.categorie_logement}}</p>
            <small id="emailHelp" class="form-text text-muted">{{ annonce.address.rue }} {{annonce.address.voie}}, {{annonce.address.ville}} - {{annonce.address.zipCode}}</small>
         </div>
          <div class="col-4">
          <h4 class="d-flex justify-content-between align-items-center mb-3">
            <span class="text-muted">Votre commande</span>
          </h4>
          <ul class="list-group mb-3" id="panier">
            <li class="list-group-item d-flex justify-content-between lh-condensed">
              <div>
                <h6 class="my-0">{{annonce.titre_logement}}</h6>
                <small class="text-muted">{{annonce.categorie_logement}}</small>
              </div>
              <span class="text-muted">{{annonce.loyer_tc}} €</span>
            </li>

          </ul>
            <li class="list-group-item d-flex justify-content-between">
                <span>Total (€)</span>
                    <strong><span id="total" name="total">{{annonce.loyer_tc}}</span> €</strong>
            </li>

              <button type="button" id="checkout-button" class="btn btn-primary mt-3">Commander</button>

        </div>
        <div class="col-8">
            <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
              <div class="carousel-inner" role="listbox" style="max-width:800px; max-height:600px !important;">
                  {% for image in myImages %}
                  {% if annonce.id == image.annonce.id %}
                    {% if forloop.counter == 1 %}
                        <div class="carousel-item active">
                          <img class="d-block w-100" src="{{image.images.url}}" alt="slide{{image.id}}">
                        </div>
                    {% else %}
                        <div class="carousel-item">
                          <img class="d-block w-100" src="{{image.images.url}}" alt="slide{{image.id}}">
                        </div>
                    {% endif%}
                  {% endif %}
                  {% endfor %}
              <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
              </a>
              <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
              </a>
            </div>
                <div class="col">
                    <div id="accordion">
                      <div class="card">
                        <div class="card-header" id="headingOne">
                          <h5 class="mb-0">
                            <button class="btn btn-link" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                              Détail logement
                            </button>
                          </h5>
                        </div>

                        <div id="collapseOne" class="collapse show" aria-labelledby="headingOne" data-parent="#accordion">
                          <div class="card-body">
                              <p>Type d'hébergement : {{ annonce.hebergement_choice }}</p>
                              <p>Catégorie du logement : {{ annonce.categorie_logement }}</p>
                              <p>Nombre de locataires : {{ annonce.nombre_personne }}</p>
                              <p>Nombre de pièces : {{ annonce.piece_couchage }}</p>
                              <p>Charges : {{annonce.charges.all|join:", " }}</p>
                              <p>Duree de location Minimale: {{annonce.dureeLocationMini}}</p>
                              <p>Duree de location Maximale: {{annonce.dureeLocationMaxi}}</p>
                              <p>Loyer (TC) : {{annonce.loyer_tc}}</p>
                              <p>Charges loyer : {{ annonce.charges_loyer }}</p>
                          </div>
                        </div>
                      </div>
                      <div class="card">
                        <div class="card-header" id="headingTwo">
                          <h5 class="mb-0">
                            <button class="btn btn-link collapsed" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                              Equipements
                            </button>
                          </h5>
                        </div>
                        <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordion">
                          <div class="card-body">
                            <p>Equipments du loyer : {{annonce.equipements.all|join:" - " }}</p>
                        </div>
                      </div>
                          <div class="card">
                        <div class="card-header" id="headingfour">
                          <h5 class="mb-0">
                            <button class="btn btn-link collapsed" data-toggle="collapse" data-target="#collapseFour" aria-expanded="false" aria-controls="collapseTwo">
                              Services
                            </button>
                          </h5>
                        </div>
                        <div id="collapseFour" class="collapse" aria-labelledby="headingTwo" data-parent="#accordion">
                          <div class="card-body">

                              {% for categorie in categorie_service %}
                              {% for service in services %}
                                  {% if service.get_categorie_display == categorie.nom %}

                                        <div class="form-check">
                                          <input class="form-check-input" type="checkbox" name="service" value="{{ service.nom }}" id="service{{ service.id }}">
                                          <label class="form-check-label" for="service{{ service.id }}">
                                              {{ service.nom }} - {{categorie.nom}}
                                          </label>
                                        </div>
                                        <script>
                                            $(document).ready(function() {
                                                  $('#service{{ service.id }}').change(function() {
                                                if(this.checked) {
                                                    var returnVal = "<li id='panier{{service.id}}' class='list-group-item d-flex justify-content-between lh-condensed'>\
                                          <div>\
                                            <h6 class='my-0'>{{service.nom}}</h6>\
                                          </div>\
                                          <span class='text-muted'>{{service.price}}€</span>\
                                        </li>"
                                            $('#panier').append(returnVal);
                                            var total
                                            total = $("#total").text()
                                            total = parseInt(total || 0,10) + parseInt({{service.price}} || 0,10);
                                            totalDiv = document.getElementById("total");
                                            totalDiv.innerHTML = total;
                                               }
                                               else{
                                               $('#panier{{service.id}}').remove();
                                                var total;
                                                total = $("#total").text();
                                                total = parseInt(total || 0,10) - parseInt({{service.price}} || 0,10);
                                                totalDiv = document.getElementById("total");
                                                totalDiv.innerHTML = total;
                                               }
                                            });
                                        });
                                        </script>
                                  {% endif %}
                              {% endfor %}
                            {% endfor %}
                        </div>
                      </div>
                      <div class="card">
                        <div class="card-header" id="headingThree">
                          <h5 class="mb-0">
                            <button class="btn btn-link collapsed" data-toggle="collapse" data-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
                              Informations Loueur
                            </button>
                          </h5>
                        </div>
                        <div id="collapseThree" class="collapse" aria-labelledby="headingThree" data-parent="#accordion">
                          <div class="card-body">
                              <p>Prenom : {{annonce.user.first_name}}</p>
                              <p>Nom : {{annonce.user.last_name}}</p>
                              <p>Téléphone de contact : {{annonce.user.telephone}}</p>
                              <p>Type de locataire : {{annonce.user.get_typelocataire_display}}</p>
                          </div>
                        </div>
                      </div>
                    </div>
                </div>
          </div>
                </div>
            </div>
        </div>
    </div>

</div>
</div>
{% csrf_token %}
  <script type="text/javascript">
  $(document).ready(function() {
   var inputs = document.getElementsByTagName('input');
     for (var i=0; i<inputs.length; i++)  {
       if (inputs[i].type == 'checkbox')   {
          inputs[i].checked = false;
        }
     }
    const csrftoken = document.querySelector('[name=csrfmiddlewaretoken]').value;
    var total;
    total = parseInt($("#total").text());
    $('body').on('DOMSubtreeModified', '#total', function(){
      total = parseInt($("#total").text());
      console.log(total);
      console.log("le total");

    });
    // Create an instance of the Stripe object with your publishable API key
    var stripe = Stripe("{{STRIPE_PUBLIC_KEY}}");
    var checkoutButton = document.getElementById("checkout-button");

    checkoutButton.addEventListener("click", function () {
    total = parseInt($("#total").text());
    url = "{% url 'create-checkout-session' annonce.id 1234 %}";
    url = url.replace(/1234/, total.toString());
      fetch(url, {
        method: "POST",
        headers: {
            'X-CSRFToken': csrftoken
        }
      })
        .then(function (response) {
          return response.json();
        })
        .then(function (session) {
          return stripe.redirectToCheckout({ sessionId: session.id });
        })
        .then(function (result) {
          // If redirectToCheckout fails due to a browser or network
          // error, you should display the localized error message to your
          // customer using error.message.
          if (result.error) {
            alert(result.error.message);
          }
        })
        .catch(function (error) {
          console.error("Error:", error);
        });
      });
    });
    </script>
{% endblock %}

templates/annonce/search/cancel.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
Canceled.
</body>
</html>

templates/annonce/search/search_page.html
{% extends 'main.html' %}
{% block content %}
<div class="container">
    <form action="." method="get" class="mt-5 row">
        <div class="input-group col-4">
          <div class="form-outline">
              <label class="form-label" for="form1">Chercher une annonce</label>
            <input type="search" id="form1" name="query_ville" class="form-control" />
        </div>
          </div>

      <div class="form-group col-4">
        <label for="select_location">Durée de location</label>
        <select class="form-control" id="select_location" name="query_location">
            <option selected value="">...</option>
          <option value="3mois">3 mois</option>
          <option value="4mois">4 mois</option>
          <option value="6mois">6 mois</option>
          <option value="1an">1 an</option>
        </select>
      </div>
        <div class="form-group col-4">
            <label for="select_locataires">Nombre de locataire</label>
            <select class="form-control" id="select_locataires" name="query_locataires">
                <option selected value="">...</option>
                <option value="1">1 locataire</option>
                <option value="2">2 locataires</option>
                <option value="3">3 locataires</option>
                <option value="4">4 locataires</option>
                <option value="5">5 locataires</option>
                <option value="6">6 locataires</option>
                <option value="7">7 locataires</option>
                <option value="8">8 locataires</option>
                <option value="9">9 locataires</option>
                <option value="10">10 locataires</option>
            </select>
        </div>
        <button class="btn btn-primary" type="submit">Chercher</button>
    </form>
    <div class="row">
    {% for annonce in annonces %}
    <div class="col-4 mt-2">
        <div class="card" style="width: 18rem;">
            {% for myImage in image %}
                {% if annonce.id == myImage.annonce.id%}
                    {% if forloop.counter == 1  %}
                        <img class="card-img-top" src="{{myImage.images.url}}" alt="logement{{annonce.id}}">
                    {% endif %}
                {% endif %}
            {% endfor %}
          <div class="card-body">
            <h5 class="card-title">{{annonce.titre_logement}}</h5>
              <small id="emailHelp" class="form-text text-muted">{{ annonce.address.rue }} {{annonce.address.voie}}, {{annonce.address.ville}} - {{annonce.address.zipCode}}</small>
            <p class="card-text">{{annonce.description}}</p>
            <a href="{% url 'detail_annonce' annonce.id %}" class="btn btn-primary">Voir plus</a>
          </div>
        </div>
        </div>

    {% endfor %}

   </div>
{% endblock %}

templates/annonce/search/success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
Success !
</body>
</html>